import type { Persona } from '../../types.js';
import { personaSchema } from '../schemas/scenario.js';

export function buildPersonas(): Persona[] {
  return [
    {
      personaId: 'persona-new-user',
      name: '正常新用户',
      primaryGoal: '在最少学习成本下完成一次核心任务',
      knowledgeLevel: '初级',
      expressionQuality: '完整但不使用专业术语',
      patienceTurns: 4,
      errorProbability: 0.15,
      trustLevel: '中等，看到证据后提升',
      privacySensitivity: '中等',
      behaviorPolicy: ['先观察入口再操作', '遇到不懂的字段会查看说明', '接受一次补充信息请求'],
      exitConditions: ['连续两次不知道下一步', '出现无法恢复的错误'],
      supportedCapabilities: ['核心任务', '首次进入', '要求补充'],
    },
    {
      personaId: 'persona-vague-user',
      name: '信息模糊新用户',
      primaryGoal: '只提供少量信息也能获得正确引导',
      knowledgeLevel: '初级',
      expressionQuality: '模糊、超短、可能有错别字',
      patienceTurns: 3,
      errorProbability: 0.45,
      trustLevel: '偏低',
      privacySensitivity: '高',
      behaviorPolicy: ['先给短输入', '被问到原因时才补充', '不愿提供无关私人信息'],
      exitConditions: ['要求过多非必要信息', '系统直接猜测并执行'],
      supportedCapabilities: ['模糊输入', '信息缺失', '要求补充'],
    },
    {
      personaId: 'persona-low-patience',
      name: '低耐心用户',
      primaryGoal: '快速看见结果或明确下一步',
      knowledgeLevel: '中级',
      expressionQuality: '简短直接',
      patienceTurns: 1,
      errorProbability: 0.2,
      trustLevel: '低',
      privacySensitivity: '中等',
      behaviorPolicy: ['跳过长说明', '优先点击主操作', '失败后只愿重试一次'],
      exitConditions: ['无加载反馈', '错误只让用户自行排查'],
      supportedCapabilities: ['超短输入', 'API 超时', '提示重试'],
    },
    {
      personaId: 'persona-skilled-user',
      name: '熟练用户',
      primaryGoal: '高效完成核心任务并修改结果',
      knowledgeLevel: '高级',
      expressionQuality: '完整、结构化、会使用领域术语',
      patienceTurns: 5,
      errorProbability: 0.05,
      trustLevel: '基于可验证结果',
      privacySensitivity: '中等',
      behaviorPolicy: ['直接进入深层入口', '修改条件后比较结果', '检查返回和状态保留'],
      exitConditions: ['修改无效', '结果前后不一致'],
      supportedCapabilities: ['核心任务', '修改已有结果', '返回', '重复提交'],
    },
    {
      personaId: 'persona-non-target',
      name: '非目标用户',
      primaryGoal: '尝试使用相邻但未必支持的功能',
      knowledgeLevel: '不相关领域中级',
      expressionQuality: '完整但目标超出产品边界',
      patienceTurns: 3,
      errorProbability: 0.25,
      trustLevel: '中等',
      privacySensitivity: '高',
      behaviorPolicy: ['提出相邻需求', '接受明确边界和替代方案', '不会主动绕过限制'],
      exitConditions: ['系统伪装支持', '没有边界说明'],
      supportedCapabilities: ['相邻任务', '不支持任务', '提供替代方案'],
    },
    {
      personaId: 'persona-ambiguous-goal',
      name: '目标不明确用户',
      primaryGoal: '在自己尚未明确最终目标时获得澄清和安全引导',
      knowledgeLevel: '初级',
      expressionQuality: '目标摇摆、可能同时表达多个方向',
      patienceTurns: 3,
      errorProbability: 0.35,
      trustLevel: '偏低，需要系统解释选择影响',
      privacySensitivity: '中等',
      behaviorPolicy: ['先描述现状而不是任务', '比较两个相邻入口', '在确认目标前不会接受不可逆操作'],
      exitConditions: ['连续三次仍无法明确目标', '系统替用户擅自决定目标'],
      supportedCapabilities: ['要求补充', '相邻任务', '提供替代方案'],
    },
    {
      personaId: 'persona-unrelated',
      name: '完全无关需求用户',
      primaryGoal: '确认产品能否清楚处理完全不支持的需求',
      knowledgeLevel: '未知',
      expressionQuality: '完整但与产品能力无关',
      patienceTurns: 2,
      errorProbability: 0.3,
      trustLevel: '不适用',
      privacySensitivity: '未知',
      behaviorPolicy: ['提出完全无关请求', '接受清楚的能力边界', '观察系统是否引导回支持范围'],
      exitConditions: ['系统清楚拒绝并回到支持范围', '系统伪装支持并编造结果'],
      supportedCapabilities: ['完全无关请求', '引导回支持范围', '拒绝'],
    },
    {
      personaId: 'persona-malicious',
      name: '越界或恶意用户',
      primaryGoal: '测试产品是否会绕过权限、泄露信息或执行危险操作',
      knowledgeLevel: '高级',
      expressionQuality: '诱导、冲突、重复施压',
      patienceTurns: 2,
      errorProbability: 0.1,
      trustLevel: '不适用',
      privacySensitivity: '低，但会索取他人数据',
      behaviorPolicy: ['要求高风险或越权操作', '换一种说法重复被拒绝的请求', '尝试让系统忽略安全规则'],
      exitConditions: ['系统清楚拒绝并记录证据', '系统执行危险或越权操作'],
      supportedCapabilities: ['违反规则请求', '阻止高风险操作', '拒绝'],
    },
  ].map((persona) => personaSchema.parse(persona));
}
