import { useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { apiRequest } from './api.js';
import { IssueDetail } from './IssueDetail.js';

type Json = Record<string, any>;
type Navigate = (target: string) => void;
const stages = ['readiness', 'scan', 'background', 'blueprint', 'cases', 'run', 'report'];
const stageLabels: Record<string, string> = { readiness: '确认项目可打开', scan: '收集页面和代码证据', background: '理解产品用途', blueprint: '确定检查标准', cases: '准备用户任务', run: '真实操作页面', report: '整理问题和建议' };
const stageExplanations: Record<string, string> = { readiness: '先确认被测页面能正常打开，避免后面的检查白跑。', scan: '看看项目有哪些页面和入口，只收集评测需要的信息。', background: '用收集到的信息理解产品是给谁用、要完成什么任务。', blueprint: '把“什么算成功、什么算卡住”整理成检查标准。', cases: '准备几条接近真实用户操作的任务。', run: '在浏览器里按任务点击和输入，并保存截图与操作轨迹。', report: '把发现整理成人话结论、问题位置和建议下一步。' };
const issueLabels: Record<string, string> = { functional_bug: '功能没有按预期工作', journey_breakpoint: '用户路径中断', discoverability_issue: '入口不容易找到', usability_issue: '操作不够顺手', path_efficiency_issue: '完成路径过长', repeated_input_issue: '需要重复输入', content_clarity_issue: '内容难以理解', interaction_feedback_issue: '操作后缺少反馈', recovery_issue: '出错后难以恢复', trust_issue: '信息不足以建立信任', accessibility_issue: '无障碍体验问题', abandonment_risk: '用户可能放弃' };
const aiProviderChoices = [
  { id: 'openai', name: 'OpenAI', detail: '使用 OpenAI API Key', model: 'gpt-5-mini', host: 'api.openai.com' },
  { id: 'deepseek', name: 'DeepSeek', detail: '使用 DeepSeek 官方 API', model: 'deepseek-v4-flash', host: 'api.deepseek.com' },
  { id: 'kimi', name: 'Kimi', detail: '使用 Kimi 中国站 API', model: 'kimi-k2.6', host: 'api.moonshot.cn' },
  { id: 'openai_compatible', name: '其他兼容服务', detail: '需要填写 API 地址和模型', model: '', host: '' },
] as const;

function useApi<T>(path: string | null) { const [data, setData] = useState<T | null>(null); const [loading, setLoading] = useState(Boolean(path)); const [error, setError] = useState<string | null>(null); const [version, setVersion] = useState(0); useEffect(() => { let alive = true; if (!path) { setData(null); setLoading(false); setError(null); return; } setLoading(true); setError(null); apiRequest<T>(path).then((value) => { if (alive) setData(value); }).catch((cause) => { if (alive) setError(cause instanceof Error ? cause.message : String(cause)); }).finally(() => { if (alive) setLoading(false); }); return () => { alive = false; }; }, [path, version]); return { data, loading, error, reload: () => setVersion((value) => value + 1) }; }
function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span>; }
function Button({ children, tone = 'primary', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { tone?: string }) { return <button className={`button ${tone}`} {...props}>{children}</button>; }
function PageHeader({ step, title, intro, action }: { step: string; title: string; intro: string; action?: ReactNode }) { return <><header className="page-header"><div><span className="eyebrow">{step}</span><h1>{title}</h1><p>{intro}</p></div>{action}</header>{title === '评测发现了什么' && <section className="result-guide"><div><span className="eyebrow">如何读懂结果</span><h2>先看结论，再决定要不要处理</h2><p>“失败”代表用户确实没完成；“阻塞”代表系统缺少前提，不能下结论；“不适用”代表项目本来就没有这项能力，不算失败。</p></div><div><span><b>通过</b>用户完成了目标</span><span><b>失败</b>发现了明确问题</span><span><b>阻塞</b>需要补充条件再测</span><span><b>不适用</b>跳过且不扣分</span></div></section>}</>; }
function Skeleton({ rows = 4 }: { rows?: number }) { return <div className="skeleton-stack" aria-label="正在加载">{Array.from({ length: rows }, (_, index) => <div className="skeleton" key={index}/>)}</div>; }
function ErrorPanel({ message, retry }: { message: string; retry?: () => void }) { return <section className="state-card error" role="alert"><span className="state-icon">!</span><div><h2>这一步没有完成</h2><p>{message}</p>{retry && <Button tone="secondary" onClick={retry}>重新尝试</Button>}</div></section>; }
function Empty({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <section className="state-card"><span className="state-icon">○</span><div><h2>{title}</h2><p>{detail}</p>{action}</div></section>; }
function Toast({ message }: { message: string | null }) { return message ? <div className="toast" role="status">{message}</div> : null; }
function AutoAdvance({ title, detail, continueLabel, onContinue, onStay }: { title: string; detail: string; continueLabel: string; onContinue: () => void; onStay: () => void }) {
  const [seconds, setSeconds] = useState(8); const continueRef = useRef(onContinue); continueRef.current = onContinue;
  useEffect(() => { const interval = window.setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); const timer = window.setTimeout(() => continueRef.current(), 8000); return () => { window.clearInterval(interval); window.clearTimeout(timer); }; }, []);
  return <section className="auto-advance" role="status"><div><span className="eyebrow">这一步已完成</span><h2>{title}</h2><p>{detail}</p><small>{seconds} 秒后自动进入下一步，你也可以留在这里慢慢看。</small></div><div className="card-actions"><Button tone="secondary" onClick={onStay}>留在这里</Button><Button onClick={onContinue}>{continueLabel}</Button></div></section>;
}
function formatDuration(value: number | null): string { if (!value) return '—'; const seconds = Math.round(value / 1000); return `${Math.floor(seconds / 60)}分${seconds % 60}秒`; }
function query(name: string): string { return new URLSearchParams(window.location.search).get(name) ?? ''; }
function CoveragePanel({ coverage }: { coverage: Json | null | undefined }) {
  if (!coverage) return <section className="coverage-panel legacy"><div><span className="eyebrow">功能覆盖证据</span><h2>这是一条旧记录，无法证明具体测过哪些功能</h2><p>旧版只保存了名称，没有逐功能运行证据，因此不会据此显示“可以继续”。</p></div></section>;
  const items = [
    ['发现功能', coverage.discoveredCount, '从代码和路由识别'],
    ['本轮计划', coverage.plannedCount, '这次准备检查'],
    ['浏览器到达', coverage.browserVisitedCount, '扫描时真实打开'],
    ['实际运行', coverage.executedCount, '按用户任务操作'],
    ['运行通过', coverage.passedCount, '任务形成完整闭环'],
    ['未运行', coverage.notRunCount, '还不能下结论'],
  ];
  return <section className={`coverage-panel ${coverage.complete && coverage.failedCount === 0 && coverage.blockedCount === 0 ? 'complete' : 'incomplete'}`}>
    <div className="coverage-heading"><div><span className="eyebrow">功能覆盖证据</span><h2>实际运行 {coverage.executedCount} / {coverage.plannedCount} 个计划功能</h2><p>“发现”不等于“测过”；只有进入真实运行并完成用户任务，才会计入通过。</p></div><Badge tone={coverage.notRunCount > 0 ? 'warning' : 'success'}>{coverage.notRunCount > 0 ? `${coverage.notRunCount} 个未运行` : '计划已跑完'}</Badge></div>
    <div className="coverage-matrix">{items.map(([label, value, detail]) => <article key={String(label)}><span>{String(label)}</span><strong>{String(value)}</strong><small>{String(detail)}</small></article>)}</div>
    {(coverage.notRunCount > 0 || coverage.failedCount > 0 || coverage.blockedCount > 0) && <p className="coverage-warning">还有未运行、失败或阻塞的功能，本次不能给出整体通过结论。</p>}
  </section>;
}

export function GuidedEvaluatePage({ active, go }: { active: Json | null; go: Navigate }) {
  const blueprint = useApi<Json>(active ? '/blueprint' : null); const history = useApi<Json[]>(active ? `/evaluations?projectId=${encodeURIComponent(active.projectId)}` : null); const depths = useApi<Json[]>(active ? `/evaluation-depths?projectId=${encodeURIComponent(active.projectId)}` : null); const health = useApi<Json>('/health');
  const [depth, setDepth] = useState('core'); const [selected, setSelected] = useState<string[]>([]); const [adjusting, setAdjusting] = useState(false); const [remoteConsent, setRemoteConsent] = useState(false); const [session, setSession] = useState<Json | null>(null); const [events, setEvents] = useState<string[]>([]); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [nextStep, setNextStep] = useState<{ target: string; title: string; detail: string } | null>(null);
  const [showConnection, setShowConnection] = useState(false); const [selectedProvider, setSelectedProvider] = useState('openai'); const [apiKey, setApiKey] = useState(''); const [providerModel, setProviderModel] = useState('gpt-5-mini'); const [providerBaseUrl, setProviderBaseUrl] = useState(''); const [connecting, setConnecting] = useState(false); const [connectionError, setConnectionError] = useState<string | null>(null); const [connectionFieldErrors, setConnectionFieldErrors] = useState<Record<string, string>>({}); const connectionInputRef = useRef<HTMLInputElement>(null);
  const capabilities = blueprint.data?.capabilities ?? []; const recommendedCapabilities = capabilities.filter((item: Json) => item.importance === 'critical' || item.importance === 'high');
  const fallbackDepths: Json[] = [{ depth: 'quick', label: '快速检查', summary: '只走 1 条最关键路径', suitableFor: '适合刚改完一个地方', durationLabel: '耗时最短', estimatedCaseCount: 1, recommended: false, recommendedReason: '马上确认刚才的修改还能使用。', includes: ['最关键的一条用户任务'], excludes: ['其他功能和异常路径'] }, { depth: 'core', label: '核心评测', summary: '检查最重要的功能，最多 3 条路径', suitableFor: '适合提测或上线前', durationLabel: '耗时适中', estimatedCaseCount: 3, recommended: true, recommendedReason: '时间与覆盖最平衡。', includes: ['必须能用和重要功能', '截图与操作轨迹'], excludes: ['低优先级完整回归'] }, { depth: 'full', label: '完整评测', summary: '检查正常、异常和回归路径', suitableFor: '适合重要版本验收', durationLabel: '耗时最长', estimatedCaseCount: null, recommended: false, recommendedReason: '发布前保留最完整证据。', includes: ['所选功能的完整案例'], excludes: ['未选择功能和不存在的 API'] }];
  const options = depths.data ?? fallbackDepths; const chosen = options.find((item: Json) => item.depth === depth) ?? options[1]; const recoverable = session?.status === 'failed' ? session : history.data?.find((item) => item.status === 'failed');
  useEffect(() => { if (adjusting && !selected.length && recommendedCapabilities.length) setSelected(recommendedCapabilities.map((item: Json) => item.id)); }, [adjusting, recommendedCapabilities.length]);
  const providerConnection = health.data?.aiProviderConnection; const providerReady = providerConnection?.configured === true || health.data?.runtime?.checks?.aiProvider?.status === 'ready';
  useEffect(() => { if (showConnection) connectionInputRef.current?.focus(); }, [showConnection]);
  const providerChoice = aiProviderChoices.find((item) => item.id === selectedProvider) ?? aiProviderChoices[0];
  function chooseProvider(provider: string) { const choice = aiProviderChoices.find((item) => item.id === provider) ?? aiProviderChoices[0]; setSelectedProvider(choice.id); setProviderModel(choice.model); setProviderBaseUrl(''); setConnectionError(null); setConnectionFieldErrors({}); }
  function customHost() { try { return new URL(providerBaseUrl).host; } catch { return ''; } }
  async function connectProvider(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const fieldErrors: Record<string, string> = {}; if (apiKey.trim().length < 8) fieldErrors.apiKey = '请粘贴至少 8 个字符的 API Key。'; if (!providerModel.trim()) fieldErrors.model = '请填写模型名称。'; if (selectedProvider === 'openai_compatible' && !providerBaseUrl.trim()) fieldErrors.baseUrl = '请填写兼容服务的 API 地址。'; if (Object.keys(fieldErrors).length) { setConnectionFieldErrors(fieldErrors); requestAnimationFrame(() => document.getElementById(fieldErrors.apiKey ? 'ai-api-key' : fieldErrors.baseUrl ? 'ai-base-url' : 'ai-model')?.focus()); return; } setConnecting(true); setConnectionError(null); setConnectionFieldErrors({}); try { const payload = selectedProvider === 'openai_compatible' ? { provider: selectedProvider, apiKey, baseUrl: providerBaseUrl, model: providerModel, confirmed: true } : { provider: selectedProvider, apiKey, model: providerModel, confirmed: true }; await apiRequest('/ai-provider/connect', { method: 'POST', body: JSON.stringify(payload) }); setApiKey(''); setShowConnection(false); setNotice(`${providerChoice.name} 已连接。现在可以按推荐方案开始评测；连接只在本次工作台运行期间有效。`); health.reload(); } catch (cause) { setConnectionError(cause instanceof Error ? cause.message : String(cause)); } finally { setConnecting(false); } }
  async function disconnectProvider() { setConnecting(true); setConnectionError(null); try { await apiRequest('/ai-provider/disconnect', { method: 'POST', body: JSON.stringify({ confirmed: true }) }); setNotice('已断开本次工作台的 AI 模型连接。'); health.reload(); } catch (cause) { setConnectionError(cause instanceof Error ? cause.message : String(cause)); } finally { setConnecting(false); } }
  function watch(evaluationId: string) { let completionHandled = false; const stream = new EventSource(`/api/evaluations/${encodeURIComponent(evaluationId)}/events`); const finish = async () => { const current = await apiRequest<Json>(`/evaluations/${evaluationId}`); setSession(current.session); if (current.session.status === 'completed' || current.session.status === 'failed') { stream.close(); history.reload(); if (current.session.status === 'failed') setError(current.session.error ?? '评测未完成。'); else if (!completionHandled) { completionHandled = true; setNotice('评测完成，可以查看本次结论和下一步。'); setNextStep({ target: `/runs?evaluationId=${encodeURIComponent(current.session.evaluationId)}`, title: 'AI 测试任务已经完成', detail: '下一页会先说明发生了什么、是不是产品问题，以及你现在应该做什么。' }); } } }; stream.addEventListener('evaluation.progress', async (raw) => { const event = JSON.parse((raw as MessageEvent).data) as Json; setEvents((items) => [...items, event.message]); try { await finish(); } catch (cause) { setError(cause instanceof Error ? `进度读取失败：${cause.message}` : '进度读取失败。'); } }); stream.onerror = async () => { stream.close(); try { await finish(); } catch { setError('评测仍在运行，但进度连接中断。请重新连接后继续查看。'); } }; }
  async function start() { if (!active) return; if (!providerReady) { setShowConnection(true); setError('请先在下方选择一个 AI 模型服务并验证 Key。连接成功后无需重启，就能开始评测。'); return; } if (!remoteConsent) { setError('请先确认本次评测的数据使用范围。'); return; } setError(null); setEvents([]); setNextStep(null); try { const started = await apiRequest<Json>('/evaluations', { method: 'POST', body: JSON.stringify({ projectId: active.projectId, depth, capabilityIds: adjusting ? selected : [], allowRemoteModel: true, allowScreenshot: false }) }); setSession(started); watch(started.evaluationId); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } }
  async function resume() { if (!recoverable) return; setError(null); try { const resumed = await apiRequest<Json>(`/evaluations/${recoverable.evaluationId}/retry`, { method: 'POST', body: JSON.stringify({ confirmed: true }) }); setSession(resumed); watch(recoverable.evaluationId); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } }
  if (!active) return <><PageHeader step="02 / 评测" title="先连接一个项目" intro="连接后系统会替你选择推荐评测。"/><Empty title="还没有当前项目" detail="返回项目页添加或选择项目。" action={<Button onClick={() => go('/projects')}>去连接项目</Button>}/></>;
  const completedStages = session?.stages?.filter((item: Json) => item.status === 'completed').length ?? 0; const currentStage = session?.currentStage ?? 'readiness';
  return <>
    <PageHeader step="02 / 评测" title="系统已经替你选好评测方案" intro="你可以直接开始；只有确实想改变范围时才需要展开选项。" action={<Badge tone="success">{active.name}</Badge>}/>
    {error && <ErrorPanel message={error} retry={recoverable ? resume : start}/>}
    {!health.loading && !providerReady && <section className="ai-connection-card" role="region" aria-labelledby="ai-connection-title">
      <div className="ai-connection-intro"><span className="state-icon">!</span><div><span className="eyebrow">开始评测前的最后一步</span><h2 id="ai-connection-title">连接一个 AI 模型</h2><p>选择你已经有 Key 的服务。EvalPilot 不会偷偷退回旧评测，也不会生成假的完成结果。</p></div></div>
      {showConnection ? <form className="ai-connect-form" onSubmit={connectProvider} noValidate>
        <fieldset className="provider-picker"><legend>1. 你使用哪家模型服务？</legend><div>{aiProviderChoices.map((choice) => <label className={selectedProvider === choice.id ? 'selected' : ''} key={choice.id}><input type="radio" name="ai-provider" value={choice.id} checked={selectedProvider === choice.id} onChange={() => chooseProvider(choice.id)} disabled={connecting}/><span><b>{choice.name}</b><small>{choice.detail}</small></span></label>)}</div></fieldset>
        <label htmlFor="ai-api-key"><b>2. 粘贴 {providerChoice.name} API Key</b><small>只保存在当前 EvalPilot 服务的内存中；关闭或重启服务后自动清除。</small></label><div><input ref={connectionInputRef} id="ai-api-key" type="password" autoComplete="off" spellCheck={false} value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder="粘贴你的 API Key" aria-invalid={Boolean(connectionFieldErrors.apiKey)} aria-describedby={connectionFieldErrors.apiKey ? 'ai-api-key-error' : undefined} disabled={connecting}/>{connectionFieldErrors.apiKey && <p id="ai-api-key-error" className="field-error">{connectionFieldErrors.apiKey}</p>}</div>
        {selectedProvider === 'openai_compatible' && <><label htmlFor="ai-base-url"><b>API 地址</b><small>填写服务商给你的 OpenAI-compatible Base URL，例如 https://example.com/v1。</small></label><div><input id="ai-base-url" type="url" value={providerBaseUrl} onChange={(event) => setProviderBaseUrl(event.target.value)} placeholder="https://example.com/v1" aria-invalid={Boolean(connectionFieldErrors.baseUrl)} aria-describedby={connectionFieldErrors.baseUrl ? 'ai-base-url-error' : undefined} disabled={connecting}/>{connectionFieldErrors.baseUrl && <p id="ai-base-url-error" className="field-error">{connectionFieldErrors.baseUrl}</p>}</div><label htmlFor="ai-model"><b>模型名称</b><small>使用服务商文档里的模型 ID。</small></label><div><input id="ai-model" value={providerModel} onChange={(event) => setProviderModel(event.target.value)} placeholder="例如 model-name" aria-invalid={Boolean(connectionFieldErrors.model)} aria-describedby={connectionFieldErrors.model ? 'ai-model-error' : undefined} disabled={connecting}/>{connectionFieldErrors.model && <p id="ai-model-error" className="field-error">{connectionFieldErrors.model}</p>}</div></>}
        <p className="provider-destination"><b>Key 将发送到：</b><span className="mono">{selectedProvider === 'openai_compatible' ? customHost() || '等待填写 API 地址' : providerChoice.host}</span></p>
        {connectionError && <p className="inline-error" role="alert">{connectionError}</p>}
        <div className="card-actions"><Button type="button" tone="secondary" disabled={connecting} onClick={() => { setShowConnection(false); setApiKey(''); setConnectionError(null); setConnectionFieldErrors({}); }}>暂时不连接</Button><Button type="submit" disabled={connecting}>{connecting ? '正在检查连接…' : '验证并连接'}</Button></div>
        <details className="advanced"><summary>模型和数据范围</summary><div>{selectedProvider !== 'openai_compatible' && <label htmlFor="ai-model"><b>模型名称</b><input id="ai-model" value={providerModel} onChange={(event) => setProviderModel(event.target.value)} disabled={connecting}/>{connectionFieldErrors.model && <p className="field-error">{connectionFieldErrors.model}</p>}</label>}<p>连接检查只读取可用模型，不生成内容。正式评测只发送你已确认的最小化页面文字；源码、Key、完整 Trace 和截图默认不发送。</p></div></details>
      </form> : <div className="card-actions"><Button onClick={() => setShowConnection(true)}>选择 AI 模型并连接</Button><Button tone="secondary" onClick={health.reload}>重新检查连接</Button></div>}
    </section>}
    {!health.loading && providerReady && <section className="ai-connected-strip" role="status"><div><b>AI 评测能力已连接</b><small>{providerConnection?.displayName ?? 'AI 模型'} · {providerConnection?.model ?? '模型未知'} · {providerConnection?.apiHost ?? '目标主机未知'} · {providerConnection?.source === 'session' ? '只在本次工作台运行期间有效' : '由启动环境提供'}</small></div>{providerConnection?.source === 'session' && <Button tone="secondary" disabled={connecting} onClick={disconnectProvider}>{connecting ? '正在断开…' : '断开本次连接'}</Button>}</section>}
    {providerReady && connectionError && <p className="inline-error" role="alert">{connectionError}</p>}
    <section id="recommended-evaluation" className="recommendation-card"><div><span className="eyebrow">推荐方案</span><h2>{chosen?.label ?? '核心评测'} · {recommendedCapabilities.length ? `检查 ${recommendedCapabilities.length} 个重要功能` : '首次运行会自动识别重要功能'}</h2><p>{chosen?.recommendedReason ?? '覆盖最常用的用户任务，时间与完整度最平衡。'}</p><div className="recommendation-facts"><span><b>会检查</b>{(chosen?.includes ?? []).join('、')}</span><span><b>预计时间</b>{chosen?.estimatedDurationMinutes ? `约 ${chosen.estimatedDurationMinutes} 分钟` : chosen?.durationLabel ?? '适中'}</span><span><b>证据范围</b>页面文本会最小化后发送给已配置模型；截图和 Trace 默认不发送</span></div><label className="consent-row"><input type="checkbox" checked={remoteConsent} onChange={(event) => setRemoteConsent(event.target.checked)}/><span><b>我同意本次使用已配置 AI 模型</b><small>不会发送源码、密钥、完整 Trace 或截图。</small></span></label></div><Button disabled={session?.status === 'running' || !providerReady || !remoteConsent} onClick={start}>{session?.status === 'running' ? '正在评测…' : adjusting ? '按当前选择开始' : '按推荐方案开始'}</Button></section>
    <details className="adjust-options" open={adjusting} onToggle={(event) => setAdjusting((event.currentTarget as HTMLDetailsElement).open)}><summary>我想调整评测范围</summary><div><section><h3>你想检查得多仔细？</h3><div className="choice-grid">{options.map((option: Json) => <label className={`choice-card ${depth === option.depth ? 'selected' : ''}`} key={option.depth}><input type="radio" name="depth" checked={depth === option.depth} onChange={() => setDepth(option.depth)}/><div className="card-heading"><b>{option.label}</b>{option.recommended && <Badge tone="success">多数情况选这个</Badge>}</div><span>{option.summary}</span><small><b>适合：</b>{option.suitableFor}</small><small><b>会检查：</b>{option.includes?.join('、')}</small><small><b>不会检查：</b>{option.excludes?.join('、')}</small><small>{option.estimatedDurationMinutes ? `历史平均约 ${option.estimatedDurationMinutes} 分钟` : option.durationLabel}{option.estimatedCaseCount ? ` · 约 ${option.estimatedCaseCount} 个任务` : ''}</small></label>)}</div></section><section><h3>你想检查哪些功能？</h3><p className="muted">系统已勾选必须能用和重要功能；取消后本轮不会检查它。</p>{blueprint.loading ? <Skeleton rows={2}/> : blueprint.error ? <p className="evidence-boundary">首次评测还没有功能清单，系统会先识别再自动选择。</p> : <div className="capability-picker">{capabilities.map((item: Json) => <label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={(event) => setSelected(event.target.checked ? [...selected, item.id] : selected.filter((id) => id !== item.id))}/><span><b>{item.name}</b><small>{item.userGoals?.[0] ?? '检查用户能否完成此功能'}</small></span><Badge tone={item.importance === 'critical' ? 'danger' : item.importance === 'high' ? 'warning' : 'neutral'}>{item.importance === 'critical' ? '必须能用' : item.importance === 'high' ? '重要功能' : '补充功能'}</Badge></label>)}</div>}</section></div></details>
    {session && <section className="diagnostic-summary" aria-live="polite"><div><span className="eyebrow">系统现在在做什么</span><h2>{session.status === 'completed' ? '检查已经完成' : session.status === 'failed' ? '检查在这里停下了' : stageLabels[currentStage]}</h2><p>{session.status === 'completed' ? '7 个步骤都已结束，你可以先回看过程，再决定何时查看结果。' : session.status === 'failed' ? '前面的结果都已保存，可以修复原因后从这里继续。' : stageExplanations[currentStage]}</p></div><strong>{completedStages} / {stages.length}<small>步骤完成</small></strong></section>}
    {nextStep && <AutoAdvance title={nextStep.title} detail={nextStep.detail} continueLabel="现在查看结果" onContinue={() => go(nextStep.target)} onStay={() => { setNextStep(null); setNotice('已暂停自动跳转，结果入口会保留在这里。'); }}/>}
    {session && <section className="pipeline" aria-label="评测进度">{stages.map((name, index) => { const item = session.stages?.find((stage: Json) => stage.name === name); return <article className={item?.status ?? 'pending'} key={name}><span>{String(index + 1).padStart(2, '0')}</span><div><b>{stageLabels[name]}</b><small>{stageExplanations[name]}</small></div><Badge tone={item?.status === 'completed' ? 'success' : item?.status === 'failed' ? 'danger' : item?.status === 'running' ? 'purple' : 'neutral'}>{item?.status === 'completed' ? '已完成' : item?.status === 'failed' ? '未完成' : item?.status === 'running' ? '进行中' : '等待'}</Badge></article>; })}</section>}
    {session && <details className="advanced diagnostic-logs"><summary>技术过程与原始日志</summary><div>{session.stages?.map((item: Json) => <p key={item.name}><b>{stageLabels[item.name] ?? item.name}：</b>{item.message ?? '暂无日志'}</p>)}{events.length > 0 && <p><b>最新事件：</b>{events.at(-1)}</p>}</div></details>}
    {session?.status === 'completed' && !nextStep && <section className="result-entry"><div><b>本次评测结果已经保存</b><p>结果页会先用人话说明结论，再展示证据和技术详情。</p></div><Button onClick={() => go(`/runs?evaluationId=${encodeURIComponent(session.evaluationId)}`)}>查看本次结论</Button></section>}
    <Toast message={notice}/>
  </>;
}

function Confirm({ title, children, busy, onClose, onConfirm, confirmLabel }: { title: string; children: ReactNode; busy: boolean; onClose: () => void; onConfirm: () => void; confirmLabel: string }) { return <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="关闭">×</button></div><div className="modal-body">{children}</div><div className="modal-actions"><Button tone="secondary" disabled={busy} onClick={onClose}>取消</Button><Button disabled={busy} onClick={onConfirm}>{busy ? '正在处理…' : confirmLabel}</Button></div></div></div>; }

export function GuidedIssuesPage({ active, go }: { active: Json | null; go: Navigate }) {
  const initialEvaluation = query('evaluationId'); const initialIssue = query('issueId'); const [evaluationId, setEvaluationId] = useState(initialEvaluation); const [feature, setFeature] = useState('all'); const [depth, setDepth] = useState('all'); const [result, setResult] = useState('all');
  const records = useApi<Json[]>(active ? `/evaluation-records?projectId=${encodeURIComponent(active.projectId)}` : null); const effectiveId = records.data?.some((item) => item.evaluationId === evaluationId) ? evaluationId : records.data?.[0]?.evaluationId ?? '';
  const issues = useApi<Json[]>(active ? `/issues?projectId=${encodeURIComponent(active.projectId)}${effectiveId ? `&evaluationId=${encodeURIComponent(effectiveId)}` : ''}` : null); const report = useApi<Json>(active && effectiveId ? `/reports/latest?projectId=${encodeURIComponent(active.projectId)}&evaluationId=${encodeURIComponent(effectiveId)}` : null);
  const [detail, setDetail] = useState<Json | null>(null); const [dismiss, setDismiss] = useState<Json | null>(null); const [fix, setFix] = useState<Json | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { if (records.data?.length && !records.data.some((item) => item.evaluationId === evaluationId)) setEvaluationId(records.data[0].evaluationId); }, [records.data, evaluationId]);
  useEffect(() => { if (initialIssue && issues.data?.length) { const selected = issues.data.find((item) => item.issueId === initialIssue); if (selected) setDetail(selected); } }, [initialIssue, issues.data]);
  async function dismissIssue() { if (!dismiss) return; setBusy(true); setError(null); try { await apiRequest(`/issues/${dismiss.issueId}/dismiss`, { method: 'POST', body: JSON.stringify({ confirmed: true }) }); setDismiss(null); issues.reload(); setMessage('已标记为暂不处理，历史证据仍会保留。'); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } }
  async function createFix() { if (!fix || !active || !effectiveId) return; setBusy(true); setError(null); try { const task = await apiRequest<Json>('/fix-tasks', { method: 'POST', body: JSON.stringify({ projectId: active.projectId, evaluationId: effectiveId, issueId: fix.issueId, confirmed: true }) }); setFix(null); go(`/fixes?fixTaskId=${encodeURIComponent(task.fixTaskId)}#fix-handoff`); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } }
  if (!active) return <><PageHeader step="03 / 问题" title="先连接一个项目" intro="连接后才能查看评测问题。"/><Empty title="没有当前项目" detail="返回项目页选择项目。" action={<Button onClick={() => go('/projects')}>去连接项目</Button>}/></>;
  if (records.loading || issues.loading) return <Skeleton rows={6}/>; if (records.error || issues.error) return <ErrorPanel message={records.error ?? issues.error ?? '问题读取失败'} retry={() => { records.reload(); issues.reload(); }}/>;
  const selectedRecord = records.data?.find((item) => item.evaluationId === effectiveId); const visible = (issues.data ?? []).filter((item) => !item.dismissed); const worst = [...visible].sort((a, b) => Number(a.severity.slice(1)) - Number(b.severity.slice(1)))[0]; const completed = selectedRecord?.verdict === 'can_continue'; const needsAttention = selectedRecord?.verdict === 'needs_attention'; const features = [...new Set((records.data ?? []).flatMap((item) => item.capabilityNames ?? []))]; const filtered = (records.data ?? []).filter((item) => (feature === 'all' || item.capabilityNames?.includes(feature)) && (depth === 'all' || item.depth === depth) && (result === 'all' || item.verdict === result));
  return <>
    <PageHeader
      step="03 / 问题"
      title="评测发现了什么"
      intro="先看实际测到了哪些功能，再判断用户能不能完成目标。"
      action={<Badge tone={completed ? 'success' : 'warning'}>{completed ? '覆盖与闭环已通过' : needsAttention ? '存在问题或覆盖缺口' : '证据不足'}</Badge>}
    />
    {error && <ErrorPanel message={error} retry={issues.reload}/>}
    <section className="record-history">
      <div className="record-toolbar">
        <div><h2>选择一份评测记录</h2><small>卡片名称、时间和结果会一起切换，不需要识别运行编号。</small></div>
        <div className="record-filters">
          <label>测了什么<select value={feature} onChange={(event) => setFeature(event.target.value)}><option value="all">全部功能</option>{features.map((name) => <option key={String(name)}>{String(name)}</option>)}</select></label>
          <label>检查范围<select value={depth} onChange={(event) => setDepth(event.target.value)}><option value="all">全部范围</option><option value="quick">快速检查</option><option value="core">核心评测</option><option value="full">完整评测</option></select></label>
          <label>结果<select value={result} onChange={(event) => setResult(event.target.value)}><option value="all">全部结果</option><option value="can_continue">可以继续</option><option value="needs_attention">需要处理</option><option value="unknown">证据不足</option></select></label>
        </div>
      </div>
      <div className="record-rail">{filtered.map((record) => <article className={`record-card ${effectiveId === record.evaluationId ? 'selected' : ''}`} key={record.evaluationId}>
        <button className="record-select" aria-pressed={effectiveId === record.evaluationId} onClick={() => { setEvaluationId(record.evaluationId); window.history.replaceState({}, '', `/issues?evaluationId=${encodeURIComponent(record.evaluationId)}#evaluation-summary`); }}>
          <span className="record-sequence">第 {record.sequenceNumber} 次</span>
          <b>{record.displayName}</b>
          <small>{record.capabilityNames?.join('、') || '没有可证明的实际运行'} · {record.depth === 'quick' ? '快速检查' : record.depth === 'full' ? '完整评测' : '核心评测'}</small>
          <div className="record-meta">
            <Badge tone={record.status === 'completed' ? 'success' : record.status === 'failed' ? 'danger' : 'purple'}>{record.status === 'completed' ? '已完成' : record.status === 'failed' ? '未完成' : '进行中'}</Badge>
            {record.coverage && <span>计划 {record.coverage.plannedCount} · 实际运行 {record.coverage.executedCount}</span>}
            <span>{record.severeIssueCount} 个严重问题</span><span>{formatDuration(record.durationMs)}</span>
            {record.notApplicableCount > 0 && <span>{record.notApplicableCount} 项不适用</span>}
          </div>
          {record.legacyEvidenceIncomplete && <em>旧记录，功能覆盖或问题证据不完整</em>}
        </button>
      </article>)}</div>
    </section>
    <CoveragePanel coverage={selectedRecord?.coverage}/>
    <section id="evaluation-summary" className="report-hero">
      <div>
        <span className="eyebrow">本次结论</span>
        <h2>{completed ? '计划功能均已运行并形成闭环' : needsAttention ? '存在明确问题或功能尚未测完' : '现有证据还不能得出整体结论'}</h2>
        <p>{worst ? `最需要先处理：${issueLabels[worst.type] ?? worst.type}` : completed ? '本轮没有发现严重问题，计划功能均有真实运行证据。' : '没有严重问题不等于已经测完，请先补齐功能级运行证据。'}</p>
        {(selectedRecord?.notApplicableCount ?? 0) > 0 && <p>{selectedRecord?.notApplicableCount} 项检查因项目没有对应能力而跳过，不计为失败。</p>}
      </div>
      <div className={`signal ${completed ? 'good' : 'warn'}`}>{completed ? '可以继续' : needsAttention ? '需要处理' : '证据不足'}</div>
    </section>
    {!visible.length ? <Empty title="当前没有待处理问题" detail="可以补测未运行功能；没有问题不代表所有页面或真实用户满意度已经被证明。" action={<Button onClick={() => go('/evaluate#recommended-evaluation')}>继续评测功能</Button>}/> : <section className="issue-board">{visible.map((issue) => <article className="issue-card" key={issue.issueId}><div className="card-heading"><Badge tone={issue.severity === 'P0' || issue.severity === 'P1' ? 'danger' : 'warning'}>{issue.severity === 'P0' || issue.severity === 'P1' ? '严重问题' : '一般问题'}</Badge><Badge>{issue.confidence === 'high' ? '证据充分' : issue.confidence === 'medium' ? '部分证据' : '需要人工确认'}</Badge></div><h2>{issueLabels[issue.type] ?? issue.type}</h2><p><b>发生了什么：</b>{issue.failureOrAbandonmentPoint ?? issue.actualPath?.at(-1) ?? '用户没有完成目标'}</p><p><b>发生位置：</b>{issue.location?.page ?? '旧记录未定位到具体页面'} · {issue.location?.target ?? issue.location?.stepLabel ?? '尚未定位到具体控件'}</p><p><b>建议改法：</b>{issue.resolutionSteps?.[0] ?? issue.recommendation}</p><div className="card-actions"><Button onClick={() => setDetail(issue)}>查看分步证据和解决方法</Button><Button tone="secondary" onClick={() => setDismiss(issue)}>暂不处理</Button><Button tone="secondary" onClick={() => setFix(issue)}>生成 Codex 修复任务</Button></div></article>)}</section>}
    {detail && <IssueDetail issue={detail} onClose={() => setDetail(null)} onDismiss={() => { setDismiss(detail); setDetail(null); }} onFix={() => { setFix(detail); setDetail(null); }}/>}
    {dismiss && <Confirm title="暂不处理这个问题？" busy={busy} onClose={() => setDismiss(null)} onConfirm={dismissIssue} confirmLabel="确认暂不处理"><p>问题会从待办列表隐藏，但证据和历史记录仍会保留。</p></Confirm>}
    {fix && <Confirm title="生成 Codex 修复任务？" busy={busy} onClose={() => setFix(null)} onConfirm={createFix} confirmLabel="确认生成任务"><p><b>{issueLabels[fix.type] ?? fix.type}</b></p><p>{fix.resolutionSteps?.[0] ?? fix.recommendation}</p><p>EvalPilot 只会生成包含问题位置、证据和验收标准的 <span className="mono">task.md</span> 与 <span className="mono">task.json</span>，当前不会自动修改你的代码。</p></Confirm>}
    <Toast message={message}/>
  </>;
}
