import { z } from 'zod';
import { httpUrlSchema } from '../config/schema.js';
import { storageIdSchema } from '../eval-set/schemas.js';

const agentProviderSchema = z.enum(['codex', 'claude_code', 'antigravity']);
export const agentCapabilitiesSchema = z.object({ workspaceDiscovery: z.boolean(), directFix: z.boolean(), taskPackageHandoff: z.boolean() });
export const agentConnectionSchema = z.object({ provider: agentProviderSchema, displayName: z.string().min(1), installed: z.boolean(), desktopInstalled: z.boolean(), version: z.string().nullable(), authStatus: z.enum(['unknown', 'ready', 'login_required']), executionMode: z.enum(['direct', 'handoff', 'unavailable']), capabilities: agentCapabilitiesSchema, blockers: z.array(z.string()), checkedAt: z.iso.datetime() });
const runtimeCheckSchema = z.object({ status: z.enum(['ready', 'missing', 'blocked']), label: z.string().min(1), detail: z.string().min(1), recoveryAction: z.string().nullable() });
const aiProviderNameSchema = z.enum(['openai', 'deepseek', 'kimi', 'openai_compatible']);
const aiProviderProtocolSchema = z.enum(['responses', 'chat_completions']);
const aiModelSchema = z.string().trim().regex(/^[A-Za-z0-9._:/-]{1,120}$/);
const apiKeySchema = z.string().trim().min(8).max(512);
const compatibleBaseUrlSchema = z.string().trim().url().max(500).superRefine((value, context) => {
  const url = new URL(value);
  const loopback = ['localhost', '127.0.0.1', '::1'].includes(url.hostname);
  if (url.protocol !== 'https:' && !(loopback && url.protocol === 'http:')) context.addIssue({ code: 'custom', message: '远程 AI 服务必须使用 HTTPS。' });
  if (url.username || url.password || url.search || url.hash) context.addIssue({ code: 'custom', message: 'AI 服务地址不能包含账号、密码、查询参数或片段。' });
});
export const aiProviderConnectionStatusSchema = z.object({ provider: aiProviderNameSchema.nullable(), displayName: z.string().min(1).nullable(), configured: z.boolean(), source: z.enum(['environment', 'session']).nullable(), protocol: aiProviderProtocolSchema.nullable(), apiHost: z.string().min(1).nullable(), model: z.string().min(1).nullable(), connectedAt: z.iso.datetime().nullable() }).strict();
const presetProviderRequestSchema = z.object({ provider: z.enum(['openai', 'deepseek', 'kimi']), apiKey: apiKeySchema, model: aiModelSchema.optional(), confirmed: z.literal(true) }).strict();
const compatibleProviderRequestSchema = z.object({ provider: z.literal('openai_compatible'), apiKey: apiKeySchema, baseUrl: compatibleBaseUrlSchema, model: aiModelSchema, confirmed: z.literal(true) }).strict();
export const aiProviderConnectionRequestSchema = z.discriminatedUnion('provider', [presetProviderRequestSchema, compatibleProviderRequestSchema]);
export const aiProviderDisconnectRequestSchema = z.object({ confirmed: z.literal(true) }).strict();
export const runtimeReadinessSchema = z.object({ packageVersion: z.string().min(1), contractVersion: z.literal('0.6.0'), platform: z.string().min(1), nodeVersion: z.string().min(1), dataRoot: z.string().min(1), checks: z.object({ node: runtimeCheckSchema, chromium: runtimeCheckSchema, git: runtimeCheckSchema, aiProvider: runtimeCheckSchema }), agents: z.array(agentConnectionSchema), blockingIssues: z.array(z.string()), recoveryActions: z.array(z.string()), checkedAt: z.iso.datetime() });
export const dashboardHealthSchema = z.object({ status: z.literal('ok'), packageVersion: z.string().min(1), contractVersion: z.literal('0.6.0'), capabilities: z.array(z.string()), runtime: runtimeReadinessSchema, aiProviderConnection: aiProviderConnectionStatusSchema.optional() });
export const projectProfileSchema = z.object({ projectId: z.string().regex(/^[a-z0-9][a-z0-9-]{1,63}$/), name: z.string().min(1), projectRoot: z.string().min(1), targetUrl: httpUrlSchema, outputDir: z.string().min(1), browser: z.literal('chromium'), startCommand: z.string().min(1).nullable(), status: z.enum(['ready', 'stopped', 'unreachable', 'evaluating', 'needs_attention']), importSource: z.union([agentProviderSchema, z.enum(['folder', 'manual', 'legacy'])]).default('legacy'), preferredAgent: agentProviderSchema.nullable().default(null), createdAt: z.iso.datetime(), updatedAt: z.iso.datetime(), lastOpenedAt: z.iso.datetime() });
export const projectRegistrySchema = z.object({ version: z.literal(1), activeProjectId: z.string().nullable(), projects: z.array(projectProfileSchema) });
export const createProjectInputSchema = z.object({ name: z.string().min(1).optional(), projectRoot: z.string().min(1), targetUrl: httpUrlSchema, startCommand: z.string().min(1).nullable().optional(), importSource: z.union([agentProviderSchema, z.enum(['folder', 'manual'])]).default('manual'), preferredAgent: agentProviderSchema.nullable().default(null) });
export const evaluationRequestSchema = z.object({ projectId: z.string().min(1), depth: z.enum(['quick', 'core', 'full']).default('core'), capabilityIds: z.array(z.string()).default([]), competitorSnapshotIds: z.array(z.string()).max(3).default([]), allowRemoteModel: z.literal(true), allowScreenshot: z.boolean().default(false) });
export const evaluationCapabilityCoverageSchema = z.object({ capabilityId: z.string().min(1), capabilityName: z.string().min(1), entryPoint: z.string().nullable(), discovered: z.boolean(), browserVisited: z.boolean(), executionStatus: z.enum(['passed', 'failed', 'blocked', 'not_applicable', 'not_run']), runIds: z.array(z.string()), reason: z.string().nullable() }).strict();
export const evaluationCoverageSummarySchema = z.object({ discoveredCount: z.number().int().nonnegative(), plannedCount: z.number().int().nonnegative(), browserVisitedCount: z.number().int().nonnegative(), executedCount: z.number().int().nonnegative(), passedCount: z.number().int().nonnegative(), failedCount: z.number().int().nonnegative(), blockedCount: z.number().int().nonnegative(), notApplicableCount: z.number().int().nonnegative(), notRunCount: z.number().int().nonnegative(), complete: z.boolean(), capabilities: z.array(evaluationCapabilityCoverageSchema) }).strict();
const evaluationIssueFixTaskRequestSchema = z.object({ projectId: storageIdSchema, evaluationId: storageIdSchema, issueId: storageIdSchema, confirmed: z.literal(true) }).strict();
const findingFixTaskRequestSchema = z.object({ projectId: storageIdSchema, findingId: storageIdSchema, confirmed: z.literal(true) }).strict();
const badcaseFixTaskRequestSchema = z.object({ projectId: storageIdSchema, badcaseId: storageIdSchema, confirmed: z.literal(true) }).strict();
export const fixTaskRequestSchema = z.union([evaluationIssueFixTaskRequestSchema, findingFixTaskRequestSchema, badcaseFixTaskRequestSchema]);
export const agentRunRequestSchema = z.object({ confirmed: z.literal(true), adapter: z.enum(['codex', 'claude_code', 'antigravity', 'task_package']).default('codex') });
export const applyFixRequestSchema = z.object({ confirmed: z.literal(true), agentRunId: z.string().min(1) });
export const workspaceCandidateRequestSchema = z.object({ confirmed: z.literal(true), providers: z.array(agentProviderSchema).default(['codex', 'claude_code', 'antigravity']) });
export const evaluationRenameSchema = z.object({ customName: z.string().trim().min(1).max(80).nullable() });
export const competitorSearchSchema = z.object({ projectId: z.string().min(1), capabilityId: z.string().nullable().default(null), query: z.string().trim().min(2).max(120), sources: z.array(z.enum(['github', 'apple_app_store', 'external_url'])).min(1), storefront: z.string().length(2).default('CN'), externalUrl: httpUrlSchema.optional() });
export const competitorSnapshotRequestSchema = z.object({ projectId: z.string().min(1), capabilityId: z.string().nullable().default(null), query: z.string().min(1), candidate: z.object({ candidateId: z.string().min(1), source: z.enum(['github', 'apple_app_store', 'external_url']), name: z.string().min(1), summary: z.string(), sourceUrl: httpUrlSchema, imageUrls: z.array(httpUrlSchema).default([]), whyRelevant: z.string(), facts: z.record(z.string(), z.union([z.string(), z.number(), z.null()])), retrievedAt: z.iso.datetime() }), confirmed: z.literal(true) });
